language: cpp

branches:
  only:
    - master

env:
  global:
    - secure: "aiH0ZGvhmY7ldfRxngIZHDuWE7ZF5UpVL577hIOUW1P+t+5lOq4hXpTaJgbaEgl0ZQ9GudeFpwx+OvUoxGwLa1wofGGSygeYRl0rfui3XkNx+5RevZ+KOuRQcv+4gJ15twvhP4+XHKfE/B8HWTO5IGN+ntRn+NzXJQLUZFXnOW8=" # GH_AUTH

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install doxygen

script:
  - mkdir gh-pages && cd gh-pages || exit
  - export GIT_ROOT=`git rev-parse --show-toplevel`
  - doxygen ../docs/Doxyfile
  - cd $GIT_ROOT

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
  -   cd gh-pages/html || exit
  -   git init

  -   git config user.email "travis@example.com"
  -   git config user.name "uOFW Doc builder"

  -   git add .
  -   git commit -am "Rebuilt docs for $TRAVIS_COMMIT"
  -   git remote add origin "https://${GH_AUTH}@github.com/$TRAVIS_REPO_SLUG.git"
  -   git pull --rebase origin gh-pages
  -   git push origin gh-pages 2>&1 | sed "s/${GH_AUTH}/[secure]/gi"
  - fi

