language: cpp

branches:
  only:
  - master

env:
  global:
    - secure: "SB91L0bAcsEDczygCw9LXMCavMHxn24j3JciGgNFyX4KjJj7PIQqNYnAHss88JIe07izV6Egerlml1iWG5HZeTBuS68vrnKUzPg4iCHUHTUhYRlChH5aM13KIiaqYhH/eLOcNeXCJObBWcRXqohkuvtUpKS2aTfJpxnuSXUmLBY=" # PASSWORD

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install doxygen

script:
  - mkdir gh-pages
  - cd gh-pages
  - export GIT_ROOT=`git rev-parse --show-toplevel`
  - doxygen ../docs/Doxyfile
  - cd $GIT_ROOT

after_success:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
  -   openssl aes-256-cbc -d -a -in travis.key.enc -out travis.key -pass "pass:$PASSWORD"
  -   chmod 600 travis.key

  -   cd gh-pages/html || exit
  -   git init

  -   git config user.email "travis@travis-ci.org"
  -   git config user.name "Bob the Build Bot"

  -   git checkout --orphan gh-pages
  -   git add .
  -   git commit -am "Rebuilt docs for $TRAVIS_COMMIT"

  -   git remote add origin "git@github.com:$TRAVIS_REPO_SLUG.git"
  -   echo "$TRAVIS_BUILD_DIR"

  -   eval "$(ssh-agent)"
  -   ssh-add $TRAVIS_BUILD_DIR/travis.key
  -   git push origin +gh-pages
  - fi

