language: cpp

branches:
  except:
    - gh-pages

env:
  global:
    - secure: "aiH0ZGvhmY7ldfRxngIZHDuWE7ZF5UpVL577hIOUW1P+t+5lOq4hXpTaJgbaEgl0ZQ9GudeFpwx+OvUoxGwLa1wofGGSygeYRl0rfui3XkNx+5RevZ+KOuRQcv+4gJ15twvhP4+XHKfE/B8HWTO5IGN+ntRn+NzXJQLUZFXnOW8=" # GH_AUTH

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install doxygen
  - cd ..
  - wget https://dl.dropboxusercontent.com/u/23414835/PSPSDK/psptoolchain_1.0_amd64.deb -O psptoolchain.deb
  - sudo dpkg --install psptoolchain.deb
  - source /etc/profile.d/psptoolchain.sh
  - cd $TRAVIS_BUILD_DIR

script:
  - make -k

after_script:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' ]]; then
  -   mkdir gh-pages && cd gh-pages
  -   export GIT_ROOT=`git rev-parse --show-toplevel`
  -   doxygen ../docs/Doxyfile
  -   cd html || exit
  -   git init

  -   git config user.email "travis@example.com"
  -   git config user.name "uOFW Doc builder"

  -   git checkout --orphan master
  -   git add .
  -   git commit -am "Rebuilt docs for $TRAVIS_COMMIT"

  -   git remote add origin "https://${GH_AUTH}@github.com/$TRAVIS_REPO_SLUG.git"
  -   git push origin +master:gh-pages 2>&1 | sed "s/${GH_AUTH}/[secure]/gi"
  - fi

